data_ingestion:
  test_size: 0.20
  data_path: 'https://raw.githubusercontent.com/Arko2016/Datasets/refs/heads/master/spam.csv'

feature_engineering:
  max_features: 30

model_building:
  n_estimators: 20
  random_state: 3