data_ingestion:
  test_size: 0.30
  data_path: 
    https://raw.githubusercontent.com/Arko2016/Datasets/refs/heads/master/spam.csv
feature_engineering:
  max_features: 50
model_building:
  n_estimators: 25
  random_state: 3
